### ISSUE TITLE
Wintun excessive CPU usage compared to old driver

### ISSUE THREAD

**Issue by marknefedov** [AdguardTeam/AdGuardVPNForWindows#851]
### Please answer the following questions for yourself before submitting an issue.

- [x] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.0 (1652)

### Environment

```markdown
- OS: Windows
- Other network-level software: None
- CPU: Ryzen 2700x
```

### Which DNS server do you use?

Cloudflare DNS

### Use Wintun

- [x] yes, I do

### Issue Details

Steps to reproduce:
1. Enable wintun.
2. Enable exclusions in selective mode.
3. Open 4k youtube video to increase network load.
4. Observe high cpu usage.

[exclusions.zip](https://github.com/user-attachments/files/19217991/exclusions.zip)

### Expected Behavior

Perform as well as WPF filtering.

### Actual Behavior

CPU significantly higher than expected.

### Screenshots

<details><summary>Wintun</summary>

<img width="1491" alt="Image" src="https://github.com/user-attachments/assets/d0f8dd3f-f486-4a27-a238-c9bf79904dbe" />

</details>
<details><summary>Old driver</summary>

<img width="1385" alt="Image" src="https://github.com/user-attachments/assets/eeef8696-ede1-41fc-b914-6173e7d0bf1c" />

</details>

**Comment by shamarin** [comment]
It was fixed in latest nightly build and seams that in 2.5.1 stable version. 
Please watch https://github.com/AdguardTeam/VpnLibs/issues/61

**Comment by marknefedov** [comment]
I've updated to 2.5.1 problem still persists.

![Image](https://github.com/user-attachments/assets/45f13a8e-97a2-4f6c-953b-c97a8590bd44)

**Comment by shamarin** [comment]
> I've updated to 2.5.1 problem still persists.
> 
> ![Image](https://github.com/user-attachments/assets/45f13a8e-97a2-4f6c-953b-c97a8590bd44)

It was fixed in nightly version 2.6.0 nightly 23 (1712).

**Comment by marknefedov** [comment]
Nope
![Image](https://github.com/user-attachments/assets/6945bb77-de69-40ed-baa8-e9d8a8ca9a43)

**Comment by Vitalik93** [comment]
I'm having no issues with Wintun driver with latest version.

**Comment by AlexandrPkhm** [comment]
@marknefedov Hello! 

Could you please record the application logs from the latest nightly? We need them in order to diagnose and troubleshoot this issue.

Here's what we need you to do:

1. Go to *Settings → App settings → Logging level → Record everything*.
2. Reproduce the problem, then remember the exact time it happened.
3. Open *Support tab → Export logs and system info*.
4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
	 — include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
	 — specify the exact time when the issue occurred

**Comment by marknefedov** [comment]
After another reinstallation (I've downgraded back to stable) it stopped reproducing, so closing for now, I'll reopen if it will happen again.

**Comment by Vladislavik** [comment]
2.6.0 nightly 27 again when Vintun enabled Adguard VPN start use CPU at 20% without any traffic
